# Project: UKEengineAdder
# Makefile created by Red Panda C++ 1.2

CPP      = clang++.exe
CC       = clang.exe
WINDRES  = windres.exe
RES      = UKEengineAdder_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
CLEANOBJ  =  main.o UKEengineAdder_private.res UKEengineAdder.exe
LIBS     =  -s -static
INCS     =  
CXXINCS  =  
BIN      = UKEengineAdder.exe
CXXFLAGS = $(CXXINCS)  -O2 -pipe
CFLAGS   = $(INCS)  -O2 -pipe
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(CLEANOBJ) > NUL 2>&1

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c C:/Users/ÀŒ√˙‰ø/Documents/Projects/ABS_2.0/UKEengine/UKEengineAdder/main.cpp -o main.o $(CXXFLAGS) 

UKEengineAdder_private.res: UKEengineAdder_private.rc 
	$(WINDRES) -i UKEengineAdder_private.rc --input-format=rc -o UKEengineAdder_private.res -O coff 

