# Project: ABSMain
# Makefile created by Red Panda C++ 1.4

CPP      = clang++.exe
CC       = clang.exe
WINDRES  = windres.exe
RES      = ABSMain_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
CLEANOBJ  =  main.o ABSMain_private.res ABSMain.exe
LIBS     =  -s -mwindows -lgraphics -luuid -lmsimg32 -lgdi32 -limm32 -lole32 -loleaut32 -lwinmm -lgdiplus   -static
INCS     =  
CXXINCS  =  
BIN      = ABSMain.exe
CXXFLAGS = $(CXXINCS)  -O2 -pipe
CFLAGS   = $(INCS)  -O2 -pipe
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(CLEANOBJ) > NUL 2>&1

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c C:/Users/ÀŒ√˙‰ø/Documents/Projects/ABS_2.0/ABSMain/main.cpp -o main.o $(CXXFLAGS) 

ABSMain_private.res: ABSMain_private.rc 
	$(WINDRES) -i ABSMain_private.rc --input-format=rc -o ABSMain_private.res -O coff 

