# Project: ABSHIPSB
# Makefile created by Red Panda C++ 1.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = ABSHIPSB_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
CLEANOBJ  =  main.o ABSHIPSB_private.res ABSHIPSB.exe
LIBS     =  -s -static
INCS     =  
CXXINCS  =  
BIN      = ABSHIPSB.exe
CXXFLAGS = $(CXXINCS)  -O2 -pipe
CFLAGS   = $(INCS)  -O2 -pipe
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(CLEANOBJ) > NUL 2>&1

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c C:/Users/ÀŒ√˙‰ø/Documents/Projects/ABS_2.0/ABSHIPSB/main.cpp -o main.o $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

ABSHIPSB_private.res: ABSHIPSB_private.rc 
	$(WINDRES) -i ABSHIPSB_private.rc --input-format=rc -o ABSHIPSB_private.res -O coff 

